### ISSUE TITLE
Non-API-specific endpoints for config, enums

### ISSUE THREAD

**Issue by michquinn** [agile-learning-institute/mentorHub-person-api#38]
https://github.com/agile-learning-institute/mentorHub-person-api/blob/0ede45653ad900309a9401596f46d3d5d49c8fa4/docs/openapi-spec.yaml#L134

https://github.com/agile-learning-institute/mentorHub-person-api/blob/0ede45653ad900309a9401596f46d3d5d49c8fa4/docs/openapi-spec.yaml#L123

Wouldn't this cause conflicts with other APIs? How would the UI services get the configuration data and enums for their corresponding API unless the endpoints were something like `/api/person/config`, `/api/person/enums`?

**Comment by FlatBallFlyer** [comment]
I believe this is a routing issue. If the ngnix container that serves up the UI is used as a proxy for the API, then the UI is calling it's own ngnix instance, which is responsible for routing requests to the correct API endpoint. Networking wise, that ngnix container can only connect to it's own API. These are security best practices for networking, they minimize the horizontal atack surface of a system. K8S and SDN make this possible. The existing ngnix configuration does not do this, but that is my preferred fix for this problem.
